name: Web APP

on:
  workflow_dispatch:

env:
  APP_LOCATION: "./shortix-web-app/"

permissions:
  id-token: write
  contents: read

jobs:
  build_and_deploy_dev:
    runs-on: ubuntu-latest
    name: "Build and Deploy to Development"
    environment: Development
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: "build"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}

  build_and_deploy_stg:
    runs-on: ubuntu-latest
    name: "Build and Deploy to Staging"
    environment: Staging
    needs: build_and_deploy_dev
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: "build"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}

  build_and_deploy_prd:
    runs-on: ubuntu-latest
    name: "Build and Deploy to Production"
    environment: Production
    needs: build_and_deploy_stg
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          lfs: false

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ vars.AZURE_CLIENT_ID }}
          tenant-id: ${{ vars.AZURE_TENANT_ID }}
          subscription-id: ${{ vars.AZURE_SUBSCRIPTION_ID }}

      - name: Build And Deploy
        uses: Azure/static-web-apps-deploy@v1
        with:
          action: "upload"
          app_location: ${{ env.APP_LOCATION }}
          output_location: "build"
        env:
          REACT_APP_CLIENT_ID: ${{ secrets.REACT_APP_CLIENT_ID }}
          REACT_APP_AUTHORITY: ${{ secrets.REACT_APP_AUTHORITY }}
          REACT_APP_API_ENDPOINT: ${{ vars.REACT_APP_API_ENDPOINT }}
